# We are using version 2 for compatibility with Portainer
version: "2"
services:
  vault:
    restart: always
    container_name: vault
    image: vault:latest
    networks:
      - automation_network
    ports:
      - 8200:8200
    volumes:
      - /etc/container_data/vault:/vault
      - /etc/container_data/vault/config:/vault/config
      - /etc/container_data/vault/file:/vault/file
      - /etc/container_data/vault/logs:/vault/logs
    environment:
      - VAULT_ADDR=http://0.0.0.0:8200
    cap_add:
      - IPC_LOCK
    command: vault server -config=/vault/config/config.hcl

networks:
  automation_network:
    external:
      name: automation_network
