# We are using version 2 for compatibility with Portainer
version: "2"
services:
  reverse_proxy:
    restart: always
    container_name: reverse_proxy
    image: nginx:latest
    ports:
      - 80:80
      - 443:443
    volumes:
      - /etc/container_data/reverse_proxy:/etc/nginx
      - /etc/container_data/certs:/certs
